name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: .node-version
      - run: pnpm install --frozen-lockfile
      - name: Lint commits
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            pnpm exec commitlint \
              --from ${{ github.event.pull_request.base.sha }} \
              --to ${{ github.event.pull_request.head.sha }} \
              --verbose
          else
            pnpm exec commitlint --last --verbose
          fi
      - run: pnpm run lint
      - run: pnpm run build
      - run: xvfb-run -a pnpm run test
      - run: npx playwright install --with-deps chromium
      - run: xvfb-run -a pnpm run test:e2e
