name: Publish
on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: .node-version
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      - name: Package extension
        run: pnpm run package

      - name: Publish to VS Code Marketplace
        run: pnpm run publish:vsce
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        run: pnpm run publish:ovsx
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true
